package org.usfirst.frc3620.FRC3620_DancingWasher;

import org.usfirst.frc3620.FRC3620_DancingWasher.commands.*;

import edu.wpi.first.wpilibj.buttons.JoystickButton;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.*;


/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI {
    //// TRIGGERING COMMANDS WITH BUTTONS
    // Once you have a button, it's trivial to bind it to a button in one of
    // three ways:
    
    // Start the command when the button is pressed and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenPressed(new ExampleCommand());
    
    // Run the command while the button is being held down and interrupt it once
    // the button is released.
    // button.whileHeld(new ExampleCommand());
    
    // Start the command when the button is released  and let it run the command
    // until it is finished as determined by it's isFinished method.
    // button.whenReleased(new ExampleCommand());

    
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public JoystickButton liftLidButton;
    public JoystickButton dropLidButton;
    public JoystickButton shootSafetyLB;
    public JoystickButton shootSafetyRB;
    public Joystick driveJoystick;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public OI() {
        driveJoystick = new Joystick(0);
        
        shootSafetyRB = new JoystickButton(driveJoystick, 7);
        shootSafetyRB.whileHeld(new EnableShootRB());
        shootSafetyLB = new JoystickButton(driveJoystick, 6);
        shootSafetyLB.whileHeld(new EnableShootLB());
        dropLidButton = new JoystickButton(driveJoystick, 3);
        dropLidButton.whenPressed(new DropLidCommand());
        liftLidButton = new JoystickButton(driveJoystick, 4);
        liftLidButton.whenPressed(new LiftLidCommand());

	    
        // SmartDashboard Buttons
        SmartDashboard.putData("LiftLidCommand", new LiftLidCommand());

        SmartDashboard.putData("DropLidCommand", new DropLidCommand());
        
        SmartDashboard.putData("Fill 1 Command", new FillCommand(1));
        SmartDashboard.putData("Fill 2 Command", new FillCommand(2));
        SmartDashboard.putData("Fill 3 Command", new FillCommand(3));

        SmartDashboard.putData("Shoot 1 Command", new ShootCommand(1));
        SmartDashboard.putData("Shoot 2 Command", new ShootCommand(2));
        SmartDashboard.putData("Shoot 3 Command", new ShootCommand(3));

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
    
    public Joystick getDriveJoystick() {
        return driveJoystick;
    }
}
